// Code generated by MockGen. DO NOT EDIT.
// Source: ./example/service_example.go

// Package mock_example is a generated GoMock package.
package mock_example

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockIService is a mock of IService interface.
type MockIService struct {
	ctrl     *gomock.Controller
	recorder *MockIServiceMockRecorder
}

// MockIServiceMockRecorder is the mock recorder for MockIService.
type MockIServiceMockRecorder struct {
	mock *MockIService
}

// NewMockIService creates a new mock instance.
func NewMockIService(ctrl *gomock.Controller) *MockIService {
	mock := &MockIService{ctrl: ctrl}
	mock.recorder = &MockIServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIService) EXPECT() *MockIServiceMockRecorder {
	return m.recorder
}

// DoSomething mocks base method.
func (m *MockIService) DoSomething() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "DoSomething")
}

// DoSomething indicates an expected call of DoSomething.
func (mr *MockIServiceMockRecorder) DoSomething() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DoSomething", reflect.TypeOf((*MockIService)(nil).DoSomething))
}
