name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18


      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Linting
        run: |
          pip install pre-commit
          sudo curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.46.2
          golangci-lint --version
          pre-commit run --all-files

      - name: Build
        run: go build -v ./...

      - name: Mockgen validator
        run: |
          go get github.com/golang/mock/mockgen
          go install github.com/golang/mock/mockgen
          go mod tidy && go mod verify && go mod download
          go run ./scripts/mockgen_validator.go

       
